# Generated by Django 5.2.8 on 2025-11-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_aboutus_privacypolicy_termsandconditions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
